### ISSUE TITLE
Redis connection hardcoded in released version

### ISSUE THREAD

**Issue by jas02** [sourav-py/nextlog#4]
Hi,

latest release of nextlog (1.1.1) has hardcoded connection to the redis server, which cause problems in case we want to run it on production and not just on developer laptop. In the main branch there is version of code, that allows set different redis_host and redis_port, but this is still unreleased. Could you please release this version or fix the issue with hardoded redis_host/redis_port?

Many thanks in advance.

**Comment by sourav-py** [comment]
Hi @jas02, 
I  really appreciate your interest in this library. 
The latest changes (including the ones for redis_host and redis_port) were merged recently and I am testing some scenarios. 
I apologize for the delay but I was a bit preoccupied lately. I will publish the latest version in a couple of days.

Thank you!!

**Comment by sourav-py** [comment]
Hi @jas02,
The latest version of the library is released.
Thanks, and best regards,
Sourav.

**Comment by jas02** [comment]
Many thanks @sourav-py !

Lumír

**Comment by sourav-py** [comment]
Fix deployed!!
